metrics:
    reporters:
      - type: boundary
        durationUnit: milliseconds
        rateUnit: seconds
        excludes:
          - "logback"
        includes:
          - "KafkaObservationSink.metrics.received"
          - "jvm.memory.heap.usage"
          - "HttpUserStore.auth.authorized"
        frequency: 1 second
        prefix: sasquatch
        extensions:
          - Mean
          - Count
          - MeanRate
          - 95th